### ISSUE TITLE
Caret Index is hidden when FlowDirection is RightToLeft On Material Design in C# WPF

### ISSUE THREAD

**Issue by mojtabahakimian** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2949]
### Bug explanation

I'm using 4.6.1 version of MaterialDesing in .Netfreamwork

the CaretIndex On the TextBox doesn't show until I click on the text box again, and the interesting thing is that if the text box is empty, the Caret Index is slightly out of the frame and a little unclear.

Full description with code and photo : [https://stackoverflow.com/questions/74441792/caret-index-is-hidden-when-flowdirection-is-righttoleft-on-material-design-in-c](https://stackoverflow.com/questions/74441792/caret-is-hidden-when-flowdirection-is-righttoleft-on-material-design-in-c-sharp)

**_This problem does not exist in this 3.2.0 version_**

### Version

4.6.1

**Comment by mojtabahakimian** [comment]
Same Problem :
1- [https://stackoverflow.com/questions/73835378/insertion-point-hides-at-the-start-of-line-while-using-right-to-left-flow-direct](url)

2- [https://learn.microsoft.com/en-us/answers/questions/23428/wpf-cursor-not-visible-in-text-box-first-position.html](url)

**Comment by nicolaihenriksen** [comment]
@mojtabahakimian None of the provided links are working 😢

I am curious whether the problem you see is the same as #2865 which unfortunately I have not been able to reproduce. If you can provide a small sample that illustrates the issue that would be great.

**Comment by Keboo** [comment]
I fixed the links above to point to the correct urls

**Comment by mojtabahakimian** [comment]
Thanks for fixing , those links are ok now and here is my full code that created on Visua Studio 2019 with .NetFreamwork 4.7.2

Link:

[[https://mega.nz/file/Y4wDXA7Q#t-UJFd-Dik8CJqNjDVQcWXhb4SoF5tZEHDLYenfmeLo](url)](https://mega.nz/file/Y4wDXA7Q#t-UJFd-Dik8CJqNjDVQcWXhb4SoF5tZEHDLYenfmeLo)

**Comment by mojtabahakimian** [comment]
Interestingly, this previous ### version 3.2.0 does not have this caret problem for right to left

but after this version until current version This problem still exists

**Comment by nicolaihenriksen** [comment]
@mojtabahakimian @Keboo Thanks for the updates 👍 

Funny observation. I am typically on 4K monitors using 150% scaling. In that setup I am unable to reproduce the issue using your sample solution:
![WithScaling](https://user-images.githubusercontent.com/19572699/202846178-b9c92130-6982-4267-ab24-cec43f34ada7.gif)

However, when I set the scaling to 100% (i.e. turn off scaling), then I can reproduce it:
![WithoutScaling](https://user-images.githubusercontent.com/19572699/202846195-be6fda54-4872-498a-b1a5-ee2952775e99.gif)
-- Note that the IBeam is not visible in the RTL `TextBox` in this recording.

I noted a similar visual artifact when adding the "reveal styles" for `PasswordBox`; see the last part of the description in this PR: #2828

I will dig further into it when I have some time.

**Comment by nicolaihenriksen** [comment]
@mojtabahakimian @Keboo After having a quick glance at this, I believe it can - at least in some cases - be solved by setting `UseLayoutRounding="True"` on the `TextBox`.

Further observations:
* This does **NOT** happen for the `MaterialDesignFloatingHintTextBox` style
* It happens for both the `MaterialDesignFilledTextBox` and `MaterialDesignOutlinedTextBox`

Typically, in scenarios like these, I have been able to solve them by setting `SnapToDevicePixels="True"`, but that has no effect in this case. `UseLayoutRounding` does seem to do the trick in the provided sample project though.

Using 100% scaling, I am now also able to reproduce issue #2865. However, setting `UseLayoutRounding="True"` unfortunately does not solve the issue there (in the test repo provided).

@Keboo Should we consider adding `UseLayoutRounding="True"` to the base style? Do you see any complications in doing so?

Also, perhaps a "deep dive" on `SnapToDevicePixels` and `UseLayoutRounding` in one of your streams could be an idea? You could use this issue to investigate what is happening while explaining the typical use-cases for these properties...

**Comment by nicolaihenriksen** [comment]
@Keboo @mojtabahakimian Forget my previous comment if you read it (I have deleted it). I had a little time this evening, so I tracked down the root cause I believe.

The base style for a MDIX `TextBox` has the following setter inside a trigger for `TextFieldAssist.HasFilledTextField=True` (and outlined style as well):
```xaml
<Setter Property="wpf:TextFieldAssist.TextBoxViewMargin" Value="{x:Static wpf:Constants.DefaultTextBoxViewMarginEmbedded}" />
```

The property being set here (`TextFieldAssist.TextBoxViewMargin`), is only explicitly used to set a margin on the hint text (if present). However, setting the property, invokes a callback which also sets the provided `Thickness` on the `Part_ContentHost` of the template. This is done in `TextFieldAssist.ApplyTextBoxViewMargin(Control, Thickness)`.

A proposed fix for the issue is to not set the attached property on the `TextBox`, but rather target the "hint" element directly:

```xaml
<Setter TargetName="Hint" Property="wpf:TextFieldAssist.TextBoxViewMargin" Value="{x:Static wpf:Constants.DefaultTextBoxViewMarginEmbedded}" />
```

This is of course a slight change in the `Margin` of the `PART_ContentHost`, but also what I believe to be the root cause of the issue. @Keboo I will create a PR with the change, then you can evaluate it.

**Comment by mojtabahakimian** [comment]
May I ask you to give me a full example code that fixing the caret problem ?

**Comment by nicolaihenriksen** [comment]
> May I ask you to give me a full example code that fixing the caret problem ?

You should be able to pull the latest nightly build from nuget.org and verify that it fixes the issue. It would actually be good to know if you also consider the issue fixed with the changes in PR #2958.

I was able to reproduce the issue, and those changes solved the issue in my reproduction sample. Let me know if your issue is also solved with the changes.

**Comment by mojtabahakimian** [comment]
hi please check it out this : 
![Untitled](https://user-images.githubusercontent.com/72439342/206364933-75c9fb2f-cad0-4c18-bcde-02ae341130f6.png)

**Comment by mojtabahakimian** [comment]
still caret issue for the MaterialDesignOutlinedTextBox

**Comment by nicolaihenriksen** [comment]
@mojtabahakimian Are you sure you've updated to one of the latest pre-releases (nightly releases)? I just tested with the latest nightly build (4.7.0-ci385) and the sample project you added to this issue. With that, I am unable to reproduce the issue for any of the MDIX `TextBox` styles (MaterialDesignOutlinedTextBox, MaterialDesignFilledTextBox, MaterialDesignFloatingHintTextBox). I tested both 100% scaling and 150% scaling.

![image](https://user-images.githubusercontent.com/19572699/206391423-18ac66ea-54a4-4609-aa17-86b3dd1fefbd.png)

<img width="306" alt="image" src="https://user-images.githubusercontent.com/19572699/206391464-5acb5ef1-fbae-4269-8448-5db1771c274b.png">
