### ISSUE TITLE
 Clicking on the blank leads to an error and no switch is successful

### ISSUE THREAD

**Issue by baikimi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#939]
![wrong](https://user-images.githubusercontent.com/17607439/39391600-bfbea506-4ad8-11e8-8357-7484960a0207.gif)

**Comment by jespersh** [comment]
I was experiencing the same with my loading card and setup card. I had it fixed by making a short delay in loading since the card was still animating away.
I cant see it used in your case where it is the user who controls which card to display

**Comment by SpoinkyNL** [comment]
Any chance this could be addressed? It's still an issue to this day :(

**Comment by jespersh** [comment]
I remembered I had left this comment: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1130#issuecomment-609044707

**Comment by SpoinkyNL** [comment]
Is there any chance you could PR that fix? I'm running into this issue and I'd hate to have to remove the animations because they are so lovely
